# Generated by Django 3.1.12 on 2025-03-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSettings',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('aws_region', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=255)),
                ('secret_key', models.CharField(max_length=255)),
                ('model_version', models.CharField(default='LLaMA 3.3 70B', max_length=50)),
                ('temperature', models.FloatField(default=0.5)),
                ('max_tokens', models.IntegerField(default=2048)),
                ('context_window', models.IntegerField(default=4096)),
            ],
            options={
                'db_table': 'model_settings',
            },
        ),
    ]
