# Generated by Django 3.1.12 on 2025-04-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('session_id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('conversation_history', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chatbot_chatsession',
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['session_id'], name='chatbot_cha_session_9384e5_idx'),
        ),
    ]
