# Generated by Django 3.1.12 on 2025-03-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='session_id',
            field=models.CharField(editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
