# Generated by Django 3.1.12 on 2025-05-04 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotFeedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('query', models.TextField()),
                ('response', models.TextField()),
                ('thumbs_up', models.BooleanField()),
                ('feedback', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chatbot.chatsession')),
            ],
            options={
                'db_table': 'chat_feedback',
            },
        ),
        migrations.AddIndex(
            model_name='chatbotfeedback',
            index=models.Index(fields=['timestamp'], name='chat_feedba_timesta_bab31b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotfeedback',
            index=models.Index(fields=['topic'], name='chat_feedba_topic_5a8b75_idx'),
        ),
    ]
