# Generated by Django 3.1.12 on 2025-04-02 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatFeedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('query', models.TextField()),
                ('chatbot_response', models.TextField()),
                ('thumbs_up', models.BooleanField(blank=True, null=True)),
                ('feedback_text', models.TextField(blank=True, null=True)),
                ('context', models.JSONField(blank=True, null=True)),
                ('viewed_context', models.BooleanField(default=False)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='chatbot.chatsession')),
            ],
            options={
                'db_table': 'chatbot_chatfeedback',
            },
        ),
        migrations.AddIndex(
            model_name='chatfeedback',
            index=models.Index(fields=['session'], name='chatbot_cha_session_a77621_idx'),
        ),
        migrations.AddIndex(
            model_name='chatfeedback',
            index=models.Index(fields=['timestamp'], name='chatbot_cha_timesta_cbec65_idx'),
        ),
        migrations.AddIndex(
            model_name='chatfeedback',
            index=models.Index(fields=['topic'], name='chatbot_cha_topic_78b860_idx'),
        ),
    ]
