# Generated by Django 3.1.12 on 2025-03-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPrompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_id', models.CharField(help_text='Unique prompt ID (application-level).', max_length=100, unique=True)),
                ('prompt_name', models.CharField(help_text="Prompt name (e.g., 'Default Prompt').", max_length=255)),
                ('prompt_text', models.TextField(help_text='System prompt text content.')),
                ('is_active', models.BooleanField(default=True, help_text='Is this prompt currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of prompt creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last prompt update.')),
            ],
            options={
                'db_table': 'system_prompts',
            },
        ),
    ]
