# Generated by Django 3.1.12 on 2025-03-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemprompt',
            name='id',
        ),
        migrations.AlterField(
            model_name='systemprompt',
            name='prompt_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
