# Generated by Django 3.1.12 on 2025-03-30 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('url_crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_title', models.CharField(max_length=255)),
                ('document_url', models.URLField()),
                ('file_path', models.FileField(upload_to='documents/')),
                ('pdf_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('file_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'uploaded_document',
            },
        ),
        migrations.CreateModel(
            name='DocumentChunks',
            fields=[
                ('chunk_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crawled_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_chunks', to='url_crawler.crawledurl')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_chunks', to='pdf_data.uploadeddocument')),
            ],
            options={
                'db_table': 'document_chunks',
            },
        ),
    ]
