# Generated by Django 3.1.12 on 2025-03-31 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardAnalytics',
            fields=[
                ('analytics_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('total_conversations', models.IntegerField(default=0)),
                ('total_documents', models.IntegerField(default=0)),
                ('embedding_queue', models.IntegerField(default=0)),
                ('active_crawlers', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'dashboard_analytics',
                'ordering': ['-date'],
            },
        ),
    ]
