# Generated by Django 3.1.12 on 2025-03-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(unique=True)),
                ('domain', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=200)),
                ('is_new', models.BooleanField(default=True)),
                ('first_crawled', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'crawled_url',
            },
        ),
        migrations.CreateModel(
            name='CrawlQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(unique=True)),
                ('domain', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('crawling', 'Crawling'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('http_status', models.IntegerField(default=200)),
                ('is_new', models.BooleanField(default=True)),
                ('first_crawled', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'crawl_queue',
            },
        ),
    ]
