# Generated by Django 3.1.12 on 2025-03-08 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledURL',
            fields=[
                ('crawl_id', models.AutoField(primary_key=True, serialize=False)),
                ('source_url', models.TextField()),
                ('status_code', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'crawled_url',
            },
        ),
        migrations.CreateModel(
            name='DocumentChunks',
            fields=[
                ('chunk_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('embedding', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crawled_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_chunks', to='data_processing.crawledurl')),
            ],
            options={
                'db_table': 'document_chunks',
            },
        ),
    ]
